Python DataFile handle int64 and lists
On 64-bit machines, the SciPy NetCDF library complains
when writing integers:

ValueError: NetCDF 3 does not support type int64

Now casts 'int' to 'numpy.int32' before writing

Also converts lists to NumPy arrays