Added template declarations for Intel compiler
Fails with linker errors such as

../../lib/libbout++.a(boundary_factory.o): In function `BoundaryFactory::createFromOptions(std::string const&, BoundaryRegion*)':
boundary_factory.cpp:(.text+0x74c): undefined reference to `void OptionFile::get<std::string>(std::string const&, std::string const&, std::string&, std::string const&)'

which are probably related to this:

http://www.parashift.com/c++-faq-lite/templates.html#faq-35.13

This patch should fix these errors, though I haven't found somewhere
to test this