petsc_operators: wip debugging CI failures
Test passes locally, fails in CI.

One error occurs when allocating:
```
  	Option total_cells = 4828 (grid.fci.nc)
  	Option backward_cell_number = Tensor<BoutReal> (grid.fci.nc)
  	Option  backward_cell_number = Tensor<BoutReal> (grid.fci.nc)
  	Option forward_cell_number = Tensor<BoutReal> (grid.fci.nc)
  	Option  forward_cell_number = Tensor<BoutReal> (grid.fci.nc)
  	Option cell_number = Tensor<BoutReal> (grid.fci.nc)
  	Option  cell_number = Tensor<BoutReal> (grid.fci.nc)

  STDERR:
  terminate called after throwing an instance of 'std::bad_array_new_length'
    what():  std::bad_array_new_length
  [runnervm3jyl0:12838] *** Process received signal ***
  [runnervm3jyl0:12838] Signal: Aborted (6)
  [runnervm3jyl0:12838] Signal code:  (-6)
  malloc(): invalid size (unsorted)
```

A second error is due to missing `netCDF4` library
```
 FAILED test_petsc_operators.py::test_petsc_operators - ImportError:
 DataFile: No supported NetCDF modules available -- requires netCDF4
```

but netCDF4 seems to be installed:
```
Successfully installed boutdata-0.4.0 certifi-2026.5.20 cftime-1.6.5 contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 fortranformat-2.0.3 freeqdsk-0.5.2 kiwisolver-1.5.0 matplotlib-3.10.9 mpmath-1.3.0 natsort-8.4.0 netCDF4-1.7.4 numpy-2.4.6 packaging-26.2 pillow-12.2.0 pyparsing-3.3.2 python-dateutil-2.9.0.post0 scipy-1.17.1 shapely-2.1.2 six-1.17.0 sympy-1.14.0 zoidberg-0.3.1.dev3+gfc5e428
```