Fixed SEEK_SET compile error
When using MPICH-2 on York's Tornado machine, not including mpi.h first
causes errors like

error: #error "SEEK_END is #defined but must not be for the C++ binding of MPI"

Fixed by including "globals.h" first